### ISSUE TITLE
GambasCAD vs GauchoCAD

### ISSUE THREAD

**Issue by abubelinha** [tercoide/GambasCAD#16]
Hi. I just landed in LibreDWG discussions page and found comments about GauchoCAD:
https://github.com/LibreDWG/libredwg/discussions/301#discussioncomment-189195

When I googled for GauchoCAD, I found this forum.
http://forum.gambas.one/viewtopic.php?p=2633&sid=7d3bd42eaa7fa3bee45e002e06267ca3#p2633
where I saw mentions to both GauchoCAD and GambasCAD.

So I searched both on github, but I am still wondering if they are related or not.

Thanks

**Comment by tercoide** [comment]
Hello, they are both related. We changed the name GauchoCAD for GambasCAD to improve the visibility for the Gambas programming language.
